spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moments
    username: postgres
    password: 12345
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  host: 0.0.0.0
  port: 8080

